/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "OSC1_IDAC8.h"
#include "OSC1_Square_Out_aliases.h"
#include "OSC1_Square_Out.h"
#include "OSC1_Soft_Sync_aliases.h"
#include "OSC1_Soft_Sync.h"
#include "OSC1_Freq_Timer.h"
#include "OSC1_Tri_Out_aliases.h"
#include "OSC1_Tri_Out.h"
#include "CV_IN_aliases.h"
#include "CV_IN.h"
#include "ADC_DelSig_1.h"
#include "OSC1_Triangle_Follower.h"
#include "OSC1_FM_Sign_Isr.h"
#include "OSC1_PW_In_aliases.h"
#include "OSC1_PW_In.h"
#include "OSC1_Pulse_Out_aliases.h"
#include "OSC1_Pulse_Out.h"
#include "OSC1_Comp.h"
#include "OSC1_Tri_Cap_aliases.h"
#include "OSC1_Tri_Cap.h"
#include "MIDI1_UART.h"
#include "OSC1_Saw_Out_Cap_aliases.h"
#include "OSC1_Saw_Out_Cap.h"
#include "USBMIDI_1.h"
#include "USBMIDI_1_audio.h"
#include "USBMIDI_1_cdc.h"
#include "USBMIDI_1_hid.h"
#include "USBMIDI_1_midi.h"
#include "USBMIDI_1_pvt.h"
#include "USBMIDI_1_cydmac.h"
#include "USBMIDI_1_msc.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "OSC1_IDAC8_SAW.h"
#include "OSC1_Saw_Reset_aliases.h"
#include "OSC1_Saw_Reset.h"
#include "Clock_1.h"
#include "OSC1_Saw_Follower.h"
#include "OSC1_Saw_Out_aliases.h"
#include "OSC1_Saw_Out.h"
#include "OSC1_Hard_Sync_aliases.h"
#include "OSC1_Hard_Sync.h"
#include "FM_Input_aliases.h"
#include "FM_Input.h"
#include "OSC1_Saw_Preset_aliases.h"
#include "OSC1_Saw_Preset.h"
#include "ADC_SAR_1.h"
#include "Comp_1.h"
#include "ADC_DelSig_1_AMux.h"
#include "ADC_DelSig_1_Ext_CP_Clk.h"
#include "ADC_DelSig_1_IRQ.h"
#include "ADC_DelSig_1_theACLK.h"
#include "MIDI1_UART_IntClock.h"
#include "USBMIDI_1_Dm_aliases.h"
#include "USBMIDI_1_Dm.h"
#include "USBMIDI_1_Dp_aliases.h"
#include "USBMIDI_1_Dp.h"
#include "ADC_SAR_1_IRQ.h"
#include "ADC_SAR_1_theACLK.h"
#include "ADC_SAR_1_Bypass_aliases.h"
#include "ADC_SAR_1_Bypass.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

